// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ahpsoolwxfcpczwvyfzc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFocHNvb2x3eGZjcGN6d3Z5ZnpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NjU5NzksImV4cCI6MjA3MDI0MTk3OX0.pVqxKLAclDeNVmrAaNi-m3xjafgfcN0gL775s6lCiB8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});